//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.CourfursaWebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CourfursaWebServices.WebServiceKategoriSoap")]
    public interface WebServiceKategoriSoap {
        
        // CODEGEN: Generating message contract since element name getKategoriListAndAddResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getKategoriListAndAdd", ReplyAction="*")]
        test.CourfursaWebServices.getKategoriListAndAddResponse getKategoriListAndAdd(test.CourfursaWebServices.getKategoriListAndAddRequest request);
        
        // CODEGEN: Generating message contract since element name AddEtveEtUrunuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddEtveEtUrunu", ReplyAction="*")]
        test.CourfursaWebServices.AddEtveEtUrunuResponse AddEtveEtUrunu(test.CourfursaWebServices.AddEtveEtUrunuRequest request);
        
        // CODEGEN: Generating message contract since element name TavukveHindiUrunuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TavukveHindiUrunu", ReplyAction="*")]
        test.CourfursaWebServices.TavukveHindiUrunuResponse TavukveHindiUrunu(test.CourfursaWebServices.TavukveHindiUrunuRequest request);
        
        // CODEGEN: Generating message contract since element name MeyveUrunuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MeyveUrunu", ReplyAction="*")]
        test.CourfursaWebServices.MeyveUrunuResponse MeyveUrunu(test.CourfursaWebServices.MeyveUrunuRequest request);
        
        // CODEGEN: Generating message contract since element name insertKategoriResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertKategori", ReplyAction="*")]
        test.CourfursaWebServices.insertKategoriResponse insertKategori(test.CourfursaWebServices.insertKategoriRequest request);
        
        // CODEGEN: Generating message contract since element name BalikveDenizMahsülleriUrunuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BalikveDenizMahsülleriUrunu", ReplyAction="*")]
        test.CourfursaWebServices.BalikveDenizMahsülleriUrunuResponse BalikveDenizMahsülleriUrunu(test.CourfursaWebServices.BalikveDenizMahsülleriUrunuRequest request);
        
        // CODEGEN: Generating message contract since element name SütParseUrunuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SütParseUrunu", ReplyAction="*")]
        test.CourfursaWebServices.SütParseUrunuResponse SütParseUrunu(test.CourfursaWebServices.SütParseUrunuRequest request);
        
        // CODEGEN: Generating message contract since element name PeynirParseUrunuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PeynirParseUrunu", ReplyAction="*")]
        test.CourfursaWebServices.PeynirParseUrunuResponse PeynirParseUrunu(test.CourfursaWebServices.PeynirParseUrunuRequest request);
        
        // CODEGEN: Generating message contract since element name YumurtaVeTerayagParseUrunuResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YumurtaVeTerayagParseUrunu", ReplyAction="*")]
        test.CourfursaWebServices.YumurtaVeTerayagParseUrunuResponse YumurtaVeTerayagParseUrunu(test.CourfursaWebServices.YumurtaVeTerayagParseUrunuRequest request);
        
        // CODEGEN: Generating message contract since element name CourfursaInsertAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CourfursaInsertAll", ReplyAction="*")]
        test.CourfursaWebServices.CourfursaInsertAllResponse CourfursaInsertAll(test.CourfursaWebServices.CourfursaInsertAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKategoriListAndAddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKategoriListAndAdd", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.getKategoriListAndAddRequestBody Body;
        
        public getKategoriListAndAddRequest() {
        }
        
        public getKategoriListAndAddRequest(test.CourfursaWebServices.getKategoriListAndAddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getKategoriListAndAddRequestBody {
        
        public getKategoriListAndAddRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getKategoriListAndAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getKategoriListAndAddResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.getKategoriListAndAddResponseBody Body;
        
        public getKategoriListAndAddResponse() {
        }
        
        public getKategoriListAndAddResponse(test.CourfursaWebServices.getKategoriListAndAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getKategoriListAndAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getKategoriListAndAddResult;
        
        public getKategoriListAndAddResponseBody() {
        }
        
        public getKategoriListAndAddResponseBody(string getKategoriListAndAddResult) {
            this.getKategoriListAndAddResult = getKategoriListAndAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEtveEtUrunuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEtveEtUrunu", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.AddEtveEtUrunuRequestBody Body;
        
        public AddEtveEtUrunuRequest() {
        }
        
        public AddEtveEtUrunuRequest(test.CourfursaWebServices.AddEtveEtUrunuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEtveEtUrunuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public AddEtveEtUrunuRequestBody() {
        }
        
        public AddEtveEtUrunuRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEtveEtUrunuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEtveEtUrunuResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.AddEtveEtUrunuResponseBody Body;
        
        public AddEtveEtUrunuResponse() {
        }
        
        public AddEtveEtUrunuResponse(test.CourfursaWebServices.AddEtveEtUrunuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddEtveEtUrunuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEtveEtUrunuResult;
        
        public AddEtveEtUrunuResponseBody() {
        }
        
        public AddEtveEtUrunuResponseBody(string AddEtveEtUrunuResult) {
            this.AddEtveEtUrunuResult = AddEtveEtUrunuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TavukveHindiUrunuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TavukveHindiUrunu", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.TavukveHindiUrunuRequestBody Body;
        
        public TavukveHindiUrunuRequest() {
        }
        
        public TavukveHindiUrunuRequest(test.CourfursaWebServices.TavukveHindiUrunuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TavukveHindiUrunuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public TavukveHindiUrunuRequestBody() {
        }
        
        public TavukveHindiUrunuRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TavukveHindiUrunuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TavukveHindiUrunuResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.TavukveHindiUrunuResponseBody Body;
        
        public TavukveHindiUrunuResponse() {
        }
        
        public TavukveHindiUrunuResponse(test.CourfursaWebServices.TavukveHindiUrunuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TavukveHindiUrunuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TavukveHindiUrunuResult;
        
        public TavukveHindiUrunuResponseBody() {
        }
        
        public TavukveHindiUrunuResponseBody(string TavukveHindiUrunuResult) {
            this.TavukveHindiUrunuResult = TavukveHindiUrunuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MeyveUrunuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MeyveUrunu", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.MeyveUrunuRequestBody Body;
        
        public MeyveUrunuRequest() {
        }
        
        public MeyveUrunuRequest(test.CourfursaWebServices.MeyveUrunuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MeyveUrunuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public MeyveUrunuRequestBody() {
        }
        
        public MeyveUrunuRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MeyveUrunuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MeyveUrunuResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.MeyveUrunuResponseBody Body;
        
        public MeyveUrunuResponse() {
        }
        
        public MeyveUrunuResponse(test.CourfursaWebServices.MeyveUrunuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MeyveUrunuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MeyveUrunuResult;
        
        public MeyveUrunuResponseBody() {
        }
        
        public MeyveUrunuResponseBody(string MeyveUrunuResult) {
            this.MeyveUrunuResult = MeyveUrunuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertKategoriRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertKategori", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.insertKategoriRequestBody Body;
        
        public insertKategoriRequest() {
        }
        
        public insertKategoriRequest(test.CourfursaWebServices.insertKategoriRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertKategoriRequestBody {
        
        public insertKategoriRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertKategoriResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertKategoriResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.insertKategoriResponseBody Body;
        
        public insertKategoriResponse() {
        }
        
        public insertKategoriResponse(test.CourfursaWebServices.insertKategoriResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertKategoriResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insertKategoriResult;
        
        public insertKategoriResponseBody() {
        }
        
        public insertKategoriResponseBody(string insertKategoriResult) {
            this.insertKategoriResult = insertKategoriResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BalikveDenizMahsülleriUrunuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BalikveDenizMahsülleriUrunu", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.BalikveDenizMahsülleriUrunuRequestBody Body;
        
        public BalikveDenizMahsülleriUrunuRequest() {
        }
        
        public BalikveDenizMahsülleriUrunuRequest(test.CourfursaWebServices.BalikveDenizMahsülleriUrunuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BalikveDenizMahsülleriUrunuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public BalikveDenizMahsülleriUrunuRequestBody() {
        }
        
        public BalikveDenizMahsülleriUrunuRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BalikveDenizMahsülleriUrunuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BalikveDenizMahsülleriUrunuResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.BalikveDenizMahsülleriUrunuResponseBody Body;
        
        public BalikveDenizMahsülleriUrunuResponse() {
        }
        
        public BalikveDenizMahsülleriUrunuResponse(test.CourfursaWebServices.BalikveDenizMahsülleriUrunuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BalikveDenizMahsülleriUrunuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BalikveDenizMahsülleriUrunuResult;
        
        public BalikveDenizMahsülleriUrunuResponseBody() {
        }
        
        public BalikveDenizMahsülleriUrunuResponseBody(string BalikveDenizMahsülleriUrunuResult) {
            this.BalikveDenizMahsülleriUrunuResult = BalikveDenizMahsülleriUrunuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SütParseUrunuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SütParseUrunu", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.SütParseUrunuRequestBody Body;
        
        public SütParseUrunuRequest() {
        }
        
        public SütParseUrunuRequest(test.CourfursaWebServices.SütParseUrunuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SütParseUrunuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public SütParseUrunuRequestBody() {
        }
        
        public SütParseUrunuRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SütParseUrunuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SütParseUrunuResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.SütParseUrunuResponseBody Body;
        
        public SütParseUrunuResponse() {
        }
        
        public SütParseUrunuResponse(test.CourfursaWebServices.SütParseUrunuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SütParseUrunuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SütParseUrunuResult;
        
        public SütParseUrunuResponseBody() {
        }
        
        public SütParseUrunuResponseBody(string SütParseUrunuResult) {
            this.SütParseUrunuResult = SütParseUrunuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PeynirParseUrunuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PeynirParseUrunu", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.PeynirParseUrunuRequestBody Body;
        
        public PeynirParseUrunuRequest() {
        }
        
        public PeynirParseUrunuRequest(test.CourfursaWebServices.PeynirParseUrunuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PeynirParseUrunuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public PeynirParseUrunuRequestBody() {
        }
        
        public PeynirParseUrunuRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PeynirParseUrunuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PeynirParseUrunuResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.PeynirParseUrunuResponseBody Body;
        
        public PeynirParseUrunuResponse() {
        }
        
        public PeynirParseUrunuResponse(test.CourfursaWebServices.PeynirParseUrunuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PeynirParseUrunuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PeynirParseUrunuResult;
        
        public PeynirParseUrunuResponseBody() {
        }
        
        public PeynirParseUrunuResponseBody(string PeynirParseUrunuResult) {
            this.PeynirParseUrunuResult = PeynirParseUrunuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YumurtaVeTerayagParseUrunuRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YumurtaVeTerayagParseUrunu", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.YumurtaVeTerayagParseUrunuRequestBody Body;
        
        public YumurtaVeTerayagParseUrunuRequest() {
        }
        
        public YumurtaVeTerayagParseUrunuRequest(test.CourfursaWebServices.YumurtaVeTerayagParseUrunuRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YumurtaVeTerayagParseUrunuRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public YumurtaVeTerayagParseUrunuRequestBody() {
        }
        
        public YumurtaVeTerayagParseUrunuRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YumurtaVeTerayagParseUrunuResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YumurtaVeTerayagParseUrunuResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.YumurtaVeTerayagParseUrunuResponseBody Body;
        
        public YumurtaVeTerayagParseUrunuResponse() {
        }
        
        public YumurtaVeTerayagParseUrunuResponse(test.CourfursaWebServices.YumurtaVeTerayagParseUrunuResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YumurtaVeTerayagParseUrunuResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string YumurtaVeTerayagParseUrunuResult;
        
        public YumurtaVeTerayagParseUrunuResponseBody() {
        }
        
        public YumurtaVeTerayagParseUrunuResponseBody(string YumurtaVeTerayagParseUrunuResult) {
            this.YumurtaVeTerayagParseUrunuResult = YumurtaVeTerayagParseUrunuResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CourfursaInsertAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CourfursaInsertAll", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.CourfursaInsertAllRequestBody Body;
        
        public CourfursaInsertAllRequest() {
        }
        
        public CourfursaInsertAllRequest(test.CourfursaWebServices.CourfursaInsertAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CourfursaInsertAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int kategoriID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int marketID;
        
        public CourfursaInsertAllRequestBody() {
        }
        
        public CourfursaInsertAllRequestBody(int kategoriID, int marketID) {
            this.kategoriID = kategoriID;
            this.marketID = marketID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CourfursaInsertAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CourfursaInsertAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.CourfursaWebServices.CourfursaInsertAllResponseBody Body;
        
        public CourfursaInsertAllResponse() {
        }
        
        public CourfursaInsertAllResponse(test.CourfursaWebServices.CourfursaInsertAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CourfursaInsertAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CourfursaInsertAllResult;
        
        public CourfursaInsertAllResponseBody() {
        }
        
        public CourfursaInsertAllResponseBody(string CourfursaInsertAllResult) {
            this.CourfursaInsertAllResult = CourfursaInsertAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceKategoriSoapChannel : test.CourfursaWebServices.WebServiceKategoriSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceKategoriSoapClient : System.ServiceModel.ClientBase<test.CourfursaWebServices.WebServiceKategoriSoap>, test.CourfursaWebServices.WebServiceKategoriSoap {
        
        public WebServiceKategoriSoapClient() {
        }
        
        public WebServiceKategoriSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceKategoriSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKategoriSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceKategoriSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.getKategoriListAndAddResponse test.CourfursaWebServices.WebServiceKategoriSoap.getKategoriListAndAdd(test.CourfursaWebServices.getKategoriListAndAddRequest request) {
            return base.Channel.getKategoriListAndAdd(request);
        }
        
        public string getKategoriListAndAdd() {
            test.CourfursaWebServices.getKategoriListAndAddRequest inValue = new test.CourfursaWebServices.getKategoriListAndAddRequest();
            inValue.Body = new test.CourfursaWebServices.getKategoriListAndAddRequestBody();
            test.CourfursaWebServices.getKategoriListAndAddResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).getKategoriListAndAdd(inValue);
            return retVal.Body.getKategoriListAndAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.AddEtveEtUrunuResponse test.CourfursaWebServices.WebServiceKategoriSoap.AddEtveEtUrunu(test.CourfursaWebServices.AddEtveEtUrunuRequest request) {
            return base.Channel.AddEtveEtUrunu(request);
        }
        
        public string AddEtveEtUrunu(int kategoriID, int marketID) {
            test.CourfursaWebServices.AddEtveEtUrunuRequest inValue = new test.CourfursaWebServices.AddEtveEtUrunuRequest();
            inValue.Body = new test.CourfursaWebServices.AddEtveEtUrunuRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.AddEtveEtUrunuResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).AddEtveEtUrunu(inValue);
            return retVal.Body.AddEtveEtUrunuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.TavukveHindiUrunuResponse test.CourfursaWebServices.WebServiceKategoriSoap.TavukveHindiUrunu(test.CourfursaWebServices.TavukveHindiUrunuRequest request) {
            return base.Channel.TavukveHindiUrunu(request);
        }
        
        public string TavukveHindiUrunu(int kategoriID, int marketID) {
            test.CourfursaWebServices.TavukveHindiUrunuRequest inValue = new test.CourfursaWebServices.TavukveHindiUrunuRequest();
            inValue.Body = new test.CourfursaWebServices.TavukveHindiUrunuRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.TavukveHindiUrunuResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).TavukveHindiUrunu(inValue);
            return retVal.Body.TavukveHindiUrunuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.MeyveUrunuResponse test.CourfursaWebServices.WebServiceKategoriSoap.MeyveUrunu(test.CourfursaWebServices.MeyveUrunuRequest request) {
            return base.Channel.MeyveUrunu(request);
        }
        
        public string MeyveUrunu(int kategoriID, int marketID) {
            test.CourfursaWebServices.MeyveUrunuRequest inValue = new test.CourfursaWebServices.MeyveUrunuRequest();
            inValue.Body = new test.CourfursaWebServices.MeyveUrunuRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.MeyveUrunuResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).MeyveUrunu(inValue);
            return retVal.Body.MeyveUrunuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.insertKategoriResponse test.CourfursaWebServices.WebServiceKategoriSoap.insertKategori(test.CourfursaWebServices.insertKategoriRequest request) {
            return base.Channel.insertKategori(request);
        }
        
        public string insertKategori() {
            test.CourfursaWebServices.insertKategoriRequest inValue = new test.CourfursaWebServices.insertKategoriRequest();
            inValue.Body = new test.CourfursaWebServices.insertKategoriRequestBody();
            test.CourfursaWebServices.insertKategoriResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).insertKategori(inValue);
            return retVal.Body.insertKategoriResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.BalikveDenizMahsülleriUrunuResponse test.CourfursaWebServices.WebServiceKategoriSoap.BalikveDenizMahsülleriUrunu(test.CourfursaWebServices.BalikveDenizMahsülleriUrunuRequest request) {
            return base.Channel.BalikveDenizMahsülleriUrunu(request);
        }
        
        public string BalikveDenizMahsülleriUrunu(int kategoriID, int marketID) {
            test.CourfursaWebServices.BalikveDenizMahsülleriUrunuRequest inValue = new test.CourfursaWebServices.BalikveDenizMahsülleriUrunuRequest();
            inValue.Body = new test.CourfursaWebServices.BalikveDenizMahsülleriUrunuRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.BalikveDenizMahsülleriUrunuResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).BalikveDenizMahsülleriUrunu(inValue);
            return retVal.Body.BalikveDenizMahsülleriUrunuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.SütParseUrunuResponse test.CourfursaWebServices.WebServiceKategoriSoap.SütParseUrunu(test.CourfursaWebServices.SütParseUrunuRequest request) {
            return base.Channel.SütParseUrunu(request);
        }
        
        public string SütParseUrunu(int kategoriID, int marketID) {
            test.CourfursaWebServices.SütParseUrunuRequest inValue = new test.CourfursaWebServices.SütParseUrunuRequest();
            inValue.Body = new test.CourfursaWebServices.SütParseUrunuRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.SütParseUrunuResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).SütParseUrunu(inValue);
            return retVal.Body.SütParseUrunuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.PeynirParseUrunuResponse test.CourfursaWebServices.WebServiceKategoriSoap.PeynirParseUrunu(test.CourfursaWebServices.PeynirParseUrunuRequest request) {
            return base.Channel.PeynirParseUrunu(request);
        }
        
        public string PeynirParseUrunu(int kategoriID, int marketID) {
            test.CourfursaWebServices.PeynirParseUrunuRequest inValue = new test.CourfursaWebServices.PeynirParseUrunuRequest();
            inValue.Body = new test.CourfursaWebServices.PeynirParseUrunuRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.PeynirParseUrunuResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).PeynirParseUrunu(inValue);
            return retVal.Body.PeynirParseUrunuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.YumurtaVeTerayagParseUrunuResponse test.CourfursaWebServices.WebServiceKategoriSoap.YumurtaVeTerayagParseUrunu(test.CourfursaWebServices.YumurtaVeTerayagParseUrunuRequest request) {
            return base.Channel.YumurtaVeTerayagParseUrunu(request);
        }
        
        public string YumurtaVeTerayagParseUrunu(int kategoriID, int marketID) {
            test.CourfursaWebServices.YumurtaVeTerayagParseUrunuRequest inValue = new test.CourfursaWebServices.YumurtaVeTerayagParseUrunuRequest();
            inValue.Body = new test.CourfursaWebServices.YumurtaVeTerayagParseUrunuRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.YumurtaVeTerayagParseUrunuResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).YumurtaVeTerayagParseUrunu(inValue);
            return retVal.Body.YumurtaVeTerayagParseUrunuResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.CourfursaWebServices.CourfursaInsertAllResponse test.CourfursaWebServices.WebServiceKategoriSoap.CourfursaInsertAll(test.CourfursaWebServices.CourfursaInsertAllRequest request) {
            return base.Channel.CourfursaInsertAll(request);
        }
        
        public string CourfursaInsertAll(int kategoriID, int marketID) {
            test.CourfursaWebServices.CourfursaInsertAllRequest inValue = new test.CourfursaWebServices.CourfursaInsertAllRequest();
            inValue.Body = new test.CourfursaWebServices.CourfursaInsertAllRequestBody();
            inValue.Body.kategoriID = kategoriID;
            inValue.Body.marketID = marketID;
            test.CourfursaWebServices.CourfursaInsertAllResponse retVal = ((test.CourfursaWebServices.WebServiceKategoriSoap)(this)).CourfursaInsertAll(inValue);
            return retVal.Body.CourfursaInsertAllResult;
        }
    }
}
