//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.MakroWebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MakroWebServices.MakroServicesSoap")]
    public interface MakroServicesSoap {
        
        // CODEGEN: Generating message contract since element name InsertKirmiziEtResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertKirmiziEt", ReplyAction="*")]
        test.MakroWebServices.InsertKirmiziEtResponse InsertKirmiziEt(test.MakroWebServices.InsertKirmiziEtRequest request);
        
        // CODEGEN: Generating message contract since element name InsertSebzeResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSebze", ReplyAction="*")]
        test.MakroWebServices.InsertSebzeResponse InsertSebze(test.MakroWebServices.InsertSebzeRequest request);
        
        // CODEGEN: Generating message contract since element name InsertMeyveResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMeyve", ReplyAction="*")]
        test.MakroWebServices.InsertMeyveResponse InsertMeyve(test.MakroWebServices.InsertMeyveRequest request);
        
        // CODEGEN: Generating message contract since element name marketAdi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertMarket", ReplyAction="*")]
        test.MakroWebServices.InsertMarketResponse InsertMarket(test.MakroWebServices.InsertMarketRequest request);
        
        // CODEGEN: Generating message contract since element name InsertSütResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertSüt", ReplyAction="*")]
        test.MakroWebServices.InsertSütResponse InsertSüt(test.MakroWebServices.InsertSütRequest request);
        
        // CODEGEN: Generating message contract since element name InsertYogurtResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertYogurt", ReplyAction="*")]
        test.MakroWebServices.InsertYogurtResponse InsertYogurt(test.MakroWebServices.InsertYogurtRequest request);
        
        // CODEGEN: Generating message contract since element name InsertPeynirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertPeynir", ReplyAction="*")]
        test.MakroWebServices.InsertPeynirResponse InsertPeynir(test.MakroWebServices.InsertPeynirRequest request);
        
        // CODEGEN: Generating message contract since element name MakroInsertAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakroInsertAll", ReplyAction="*")]
        test.MakroWebServices.MakroInsertAllResponse MakroInsertAll(test.MakroWebServices.MakroInsertAllRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKirmiziEtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKirmiziEt", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertKirmiziEtRequestBody Body;
        
        public InsertKirmiziEtRequest() {
        }
        
        public InsertKirmiziEtRequest(test.MakroWebServices.InsertKirmiziEtRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKirmiziEtRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int marketID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int kategoriID;
        
        public InsertKirmiziEtRequestBody() {
        }
        
        public InsertKirmiziEtRequestBody(int marketID, int kategoriID) {
            this.marketID = marketID;
            this.kategoriID = kategoriID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertKirmiziEtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertKirmiziEtResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertKirmiziEtResponseBody Body;
        
        public InsertKirmiziEtResponse() {
        }
        
        public InsertKirmiziEtResponse(test.MakroWebServices.InsertKirmiziEtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertKirmiziEtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertKirmiziEtResult;
        
        public InsertKirmiziEtResponseBody() {
        }
        
        public InsertKirmiziEtResponseBody(string InsertKirmiziEtResult) {
            this.InsertKirmiziEtResult = InsertKirmiziEtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSebzeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSebze", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertSebzeRequestBody Body;
        
        public InsertSebzeRequest() {
        }
        
        public InsertSebzeRequest(test.MakroWebServices.InsertSebzeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSebzeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int marketID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int kategoriID;
        
        public InsertSebzeRequestBody() {
        }
        
        public InsertSebzeRequestBody(int marketID, int kategoriID) {
            this.marketID = marketID;
            this.kategoriID = kategoriID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSebzeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSebzeResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertSebzeResponseBody Body;
        
        public InsertSebzeResponse() {
        }
        
        public InsertSebzeResponse(test.MakroWebServices.InsertSebzeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSebzeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertSebzeResult;
        
        public InsertSebzeResponseBody() {
        }
        
        public InsertSebzeResponseBody(string InsertSebzeResult) {
            this.InsertSebzeResult = InsertSebzeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMeyveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMeyve", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertMeyveRequestBody Body;
        
        public InsertMeyveRequest() {
        }
        
        public InsertMeyveRequest(test.MakroWebServices.InsertMeyveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMeyveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int marketID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int kategoriID;
        
        public InsertMeyveRequestBody() {
        }
        
        public InsertMeyveRequestBody(int marketID, int kategoriID) {
            this.marketID = marketID;
            this.kategoriID = kategoriID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMeyveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMeyveResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertMeyveResponseBody Body;
        
        public InsertMeyveResponse() {
        }
        
        public InsertMeyveResponse(test.MakroWebServices.InsertMeyveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMeyveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertMeyveResult;
        
        public InsertMeyveResponseBody() {
        }
        
        public InsertMeyveResponseBody(string InsertMeyveResult) {
            this.InsertMeyveResult = InsertMeyveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMarketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMarket", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertMarketRequestBody Body;
        
        public InsertMarketRequest() {
        }
        
        public InsertMarketRequest(test.MakroWebServices.InsertMarketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMarketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string marketAdi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string marketAdresi;
        
        public InsertMarketRequestBody() {
        }
        
        public InsertMarketRequestBody(string marketAdi, string marketAdresi) {
            this.marketAdi = marketAdi;
            this.marketAdresi = marketAdresi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertMarketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertMarketResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertMarketResponseBody Body;
        
        public InsertMarketResponse() {
        }
        
        public InsertMarketResponse(test.MakroWebServices.InsertMarketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertMarketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertMarketResult;
        
        public InsertMarketResponseBody() {
        }
        
        public InsertMarketResponseBody(string InsertMarketResult) {
            this.InsertMarketResult = InsertMarketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSütRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSüt", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertSütRequestBody Body;
        
        public InsertSütRequest() {
        }
        
        public InsertSütRequest(test.MakroWebServices.InsertSütRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSütRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int marketID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int kategoriID;
        
        public InsertSütRequestBody() {
        }
        
        public InsertSütRequestBody(int marketID, int kategoriID) {
            this.marketID = marketID;
            this.kategoriID = kategoriID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertSütResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertSütResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertSütResponseBody Body;
        
        public InsertSütResponse() {
        }
        
        public InsertSütResponse(test.MakroWebServices.InsertSütResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertSütResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertSütResult;
        
        public InsertSütResponseBody() {
        }
        
        public InsertSütResponseBody(string InsertSütResult) {
            this.InsertSütResult = InsertSütResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertYogurtRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertYogurt", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertYogurtRequestBody Body;
        
        public InsertYogurtRequest() {
        }
        
        public InsertYogurtRequest(test.MakroWebServices.InsertYogurtRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertYogurtRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int marketID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int kategoriID;
        
        public InsertYogurtRequestBody() {
        }
        
        public InsertYogurtRequestBody(int marketID, int kategoriID) {
            this.marketID = marketID;
            this.kategoriID = kategoriID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertYogurtResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertYogurtResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertYogurtResponseBody Body;
        
        public InsertYogurtResponse() {
        }
        
        public InsertYogurtResponse(test.MakroWebServices.InsertYogurtResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertYogurtResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertYogurtResult;
        
        public InsertYogurtResponseBody() {
        }
        
        public InsertYogurtResponseBody(string InsertYogurtResult) {
            this.InsertYogurtResult = InsertYogurtResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPeynirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPeynir", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertPeynirRequestBody Body;
        
        public InsertPeynirRequest() {
        }
        
        public InsertPeynirRequest(test.MakroWebServices.InsertPeynirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPeynirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int marketID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int kategoriID;
        
        public InsertPeynirRequestBody() {
        }
        
        public InsertPeynirRequestBody(int marketID, int kategoriID) {
            this.marketID = marketID;
            this.kategoriID = kategoriID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertPeynirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertPeynirResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.InsertPeynirResponseBody Body;
        
        public InsertPeynirResponse() {
        }
        
        public InsertPeynirResponse(test.MakroWebServices.InsertPeynirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertPeynirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertPeynirResult;
        
        public InsertPeynirResponseBody() {
        }
        
        public InsertPeynirResponseBody(string InsertPeynirResult) {
            this.InsertPeynirResult = InsertPeynirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakroInsertAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakroInsertAll", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.MakroInsertAllRequestBody Body;
        
        public MakroInsertAllRequest() {
        }
        
        public MakroInsertAllRequest(test.MakroWebServices.MakroInsertAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakroInsertAllRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int marketID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int kategoriID;
        
        public MakroInsertAllRequestBody() {
        }
        
        public MakroInsertAllRequestBody(int marketID, int kategoriID) {
            this.marketID = marketID;
            this.kategoriID = kategoriID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakroInsertAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakroInsertAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public test.MakroWebServices.MakroInsertAllResponseBody Body;
        
        public MakroInsertAllResponse() {
        }
        
        public MakroInsertAllResponse(test.MakroWebServices.MakroInsertAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakroInsertAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MakroInsertAllResult;
        
        public MakroInsertAllResponseBody() {
        }
        
        public MakroInsertAllResponseBody(string MakroInsertAllResult) {
            this.MakroInsertAllResult = MakroInsertAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MakroServicesSoapChannel : test.MakroWebServices.MakroServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MakroServicesSoapClient : System.ServiceModel.ClientBase<test.MakroWebServices.MakroServicesSoap>, test.MakroWebServices.MakroServicesSoap {
        
        public MakroServicesSoapClient() {
        }
        
        public MakroServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MakroServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MakroServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MakroServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.InsertKirmiziEtResponse test.MakroWebServices.MakroServicesSoap.InsertKirmiziEt(test.MakroWebServices.InsertKirmiziEtRequest request) {
            return base.Channel.InsertKirmiziEt(request);
        }
        
        public string InsertKirmiziEt(int marketID, int kategoriID) {
            test.MakroWebServices.InsertKirmiziEtRequest inValue = new test.MakroWebServices.InsertKirmiziEtRequest();
            inValue.Body = new test.MakroWebServices.InsertKirmiziEtRequestBody();
            inValue.Body.marketID = marketID;
            inValue.Body.kategoriID = kategoriID;
            test.MakroWebServices.InsertKirmiziEtResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).InsertKirmiziEt(inValue);
            return retVal.Body.InsertKirmiziEtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.InsertSebzeResponse test.MakroWebServices.MakroServicesSoap.InsertSebze(test.MakroWebServices.InsertSebzeRequest request) {
            return base.Channel.InsertSebze(request);
        }
        
        public string InsertSebze(int marketID, int kategoriID) {
            test.MakroWebServices.InsertSebzeRequest inValue = new test.MakroWebServices.InsertSebzeRequest();
            inValue.Body = new test.MakroWebServices.InsertSebzeRequestBody();
            inValue.Body.marketID = marketID;
            inValue.Body.kategoriID = kategoriID;
            test.MakroWebServices.InsertSebzeResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).InsertSebze(inValue);
            return retVal.Body.InsertSebzeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.InsertMeyveResponse test.MakroWebServices.MakroServicesSoap.InsertMeyve(test.MakroWebServices.InsertMeyveRequest request) {
            return base.Channel.InsertMeyve(request);
        }
        
        public string InsertMeyve(int marketID, int kategoriID) {
            test.MakroWebServices.InsertMeyveRequest inValue = new test.MakroWebServices.InsertMeyveRequest();
            inValue.Body = new test.MakroWebServices.InsertMeyveRequestBody();
            inValue.Body.marketID = marketID;
            inValue.Body.kategoriID = kategoriID;
            test.MakroWebServices.InsertMeyveResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).InsertMeyve(inValue);
            return retVal.Body.InsertMeyveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.InsertMarketResponse test.MakroWebServices.MakroServicesSoap.InsertMarket(test.MakroWebServices.InsertMarketRequest request) {
            return base.Channel.InsertMarket(request);
        }
        
        public string InsertMarket(string marketAdi, string marketAdresi) {
            test.MakroWebServices.InsertMarketRequest inValue = new test.MakroWebServices.InsertMarketRequest();
            inValue.Body = new test.MakroWebServices.InsertMarketRequestBody();
            inValue.Body.marketAdi = marketAdi;
            inValue.Body.marketAdresi = marketAdresi;
            test.MakroWebServices.InsertMarketResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).InsertMarket(inValue);
            return retVal.Body.InsertMarketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.InsertSütResponse test.MakroWebServices.MakroServicesSoap.InsertSüt(test.MakroWebServices.InsertSütRequest request) {
            return base.Channel.InsertSüt(request);
        }
        
        public string InsertSüt(int marketID, int kategoriID) {
            test.MakroWebServices.InsertSütRequest inValue = new test.MakroWebServices.InsertSütRequest();
            inValue.Body = new test.MakroWebServices.InsertSütRequestBody();
            inValue.Body.marketID = marketID;
            inValue.Body.kategoriID = kategoriID;
            test.MakroWebServices.InsertSütResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).InsertSüt(inValue);
            return retVal.Body.InsertSütResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.InsertYogurtResponse test.MakroWebServices.MakroServicesSoap.InsertYogurt(test.MakroWebServices.InsertYogurtRequest request) {
            return base.Channel.InsertYogurt(request);
        }
        
        public string InsertYogurt(int marketID, int kategoriID) {
            test.MakroWebServices.InsertYogurtRequest inValue = new test.MakroWebServices.InsertYogurtRequest();
            inValue.Body = new test.MakroWebServices.InsertYogurtRequestBody();
            inValue.Body.marketID = marketID;
            inValue.Body.kategoriID = kategoriID;
            test.MakroWebServices.InsertYogurtResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).InsertYogurt(inValue);
            return retVal.Body.InsertYogurtResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.InsertPeynirResponse test.MakroWebServices.MakroServicesSoap.InsertPeynir(test.MakroWebServices.InsertPeynirRequest request) {
            return base.Channel.InsertPeynir(request);
        }
        
        public string InsertPeynir(int marketID, int kategoriID) {
            test.MakroWebServices.InsertPeynirRequest inValue = new test.MakroWebServices.InsertPeynirRequest();
            inValue.Body = new test.MakroWebServices.InsertPeynirRequestBody();
            inValue.Body.marketID = marketID;
            inValue.Body.kategoriID = kategoriID;
            test.MakroWebServices.InsertPeynirResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).InsertPeynir(inValue);
            return retVal.Body.InsertPeynirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        test.MakroWebServices.MakroInsertAllResponse test.MakroWebServices.MakroServicesSoap.MakroInsertAll(test.MakroWebServices.MakroInsertAllRequest request) {
            return base.Channel.MakroInsertAll(request);
        }
        
        public string MakroInsertAll(int marketID, int kategoriID) {
            test.MakroWebServices.MakroInsertAllRequest inValue = new test.MakroWebServices.MakroInsertAllRequest();
            inValue.Body = new test.MakroWebServices.MakroInsertAllRequestBody();
            inValue.Body.marketID = marketID;
            inValue.Body.kategoriID = kategoriID;
            test.MakroWebServices.MakroInsertAllResponse retVal = ((test.MakroWebServices.MakroServicesSoap)(this)).MakroInsertAll(inValue);
            return retVal.Body.MakroInsertAllResult;
        }
    }
}
