//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketlerEntities3 : DbContext
    {
        public MarketlerEntities3()
            : base("name=MarketlerEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aciklamalar> Aciklamalar { get; set; }
        public virtual DbSet<Birimler> Birimler { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Konumlar> Konumlar { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Loglar> Loglar { get; set; }
        public virtual DbSet<Sub_Kategori> Sub_Kategori { get; set; }
        public virtual DbSet<Urunler> Urunler { get; set; }
        public virtual DbSet<Marketler> Marketlers { get; set; }
    }
}
