//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loglar
    {
        public int Log_Id { get; set; }
        public int User_Id { get; set; }
        public int Urun_Id { get; set; }
        public int Konum_Id { get; set; }
    
        public virtual Konumlar Konumlar { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
