//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marketler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Marketler()
        {
            this.Urunlers = new HashSet<Urunler>();
        }
    
        public int Market_Id { get; set; }
        public string Market_Adi { get; set; }
        public int Konum_Id { get; set; }
        public string Adress { get; set; }
    
        public virtual Konumlar Konumlar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunlers { get; set; }
    }
}
