//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Kategori
    {
        public int Sub_Kategori_Id { get; set; }
        public string Sub_Kategori_Adi { get; set; }
        public int Kategori_Id { get; set; }
        public int Aciklama_Id { get; set; }
        public int Parent_Sub_Id { get; set; }
    
        public virtual Aciklamalar Aciklamalar { get; set; }
        public virtual Kategori Kategori { get; set; }
    }
}
