//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.Loglar = new HashSet<Loglar>();
        }
    
        public int Urun_Id { get; set; }
        public string Urun_Adi { get; set; }
        public Nullable<int> Birim_Id { get; set; }
        public Nullable<int> Market_Id { get; set; }
        public string Marka { get; set; }
        public Nullable<int> Kategori_Id { get; set; }
        public Nullable<double> Fiyat { get; set; }
        public string Image { get; set; }
        public Nullable<int> Aciklama_Id { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual Aciklamalar Aciklamalar { get; set; }
        public virtual Birimler Birimler { get; set; }
        public virtual Kategori Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Loglar> Loglar { get; set; }
        public virtual Marketler Marketler { get; set; }
    }
}
